source 'https://github.com/CocoaPods/Specs.git'
source 'http://192.168.10.174/wudi/SSUIKit.git'

use_frameworks!
inhibit_all_warnings!

target 'SSUIKit_Example' do
  pod 'SSUIKit', :path => '../'

  target 'SSUIKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
